all:
  children:
    domain_controllers:
      hosts:
        dc1.voughtnet.local:
        windc2.voughtnet.local:

    mbr_servers:
      hosts:
        appsrv1.voughtnet.local:
        

    workstations:
      hosts:
        win11pc1.voughtnet.local:
