all:
  children:

    domain_controllers:
      hosts:
        dc1.voughtnet.local:
          ansible_host: 192.168.10.10
        windc2.voughtnet.local:
          ansible_host: 192.168.10.11

    member_servers:
      hosts:
        appsvr1.voughtnet.local:
          ansible_host: 192.168.10.198

    workstations:
      hosts:
        win11pc1.voughtnet.local:
          ansible_host: 192.168.40.40
